# Example secrets - Replace with actual values and use external secret management
apiVersion: v1
kind: Secret
metadata:
  name: database-credentials
  namespace: shopmetrics
type: Opaque
stringData:
  product-db-url: "postgresql://user:password@product-db:5432/products"
  order-db-url: "postgresql://user:password@order-db:5432/orders"
  user-db-url: "postgresql://user:password@user-db:5432/users"
  payment-db-url: "postgresql://user:password@payment-db:5432/payments"
---
apiVersion: v1
kind: Secret
metadata:
  name: auth-credentials
  namespace: shopmetrics
type: Opaque
stringData:
  jwt-secret: "your-jwt-secret-key-change-in-production"
---
apiVersion: v1
kind: Secret
metadata:
  name: payment-credentials
  namespace: shopmetrics
type: Opaque
stringData:
  stripe-api-key: "sk_test_your_stripe_key"
  paypal-client-id: "your_paypal_client_id"
  paypal-secret: "your_paypal_secret"
