apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  namespace: shopmetrics
  labels:
    app: payment-service
    tier: backend
    critical: "true"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
        tier: backend
        critical: "true"
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8084"
        prometheus.io/path: "/metrics"
    spec:
      containers:
        - name: payment-service
          image: 543927035352.dkr.ecr.us-east-1.amazonaws.com/shopmetrics-payment-service:latest
          ports:
            - name: http
              containerPort: 8084
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: database-credentials
                  key: payment-db-url
            - name: STRIPE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: payment-credentials
                  key: stripe-api-key
            - name: PAYPAL_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: payment-credentials
                  key: paypal-client-id
          resources:
            requests:
              cpu: 300m
              memory: 512Mi
            limits:
              cpu: 1000m
              memory: 1Gi
          livenessProbe:
            httpGet:
              path: /health
              port: 8084
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /ready
              port: 8084
            initialDelaySeconds: 10
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
  namespace: shopmetrics
  labels:
    app: payment-service
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8084
      targetPort: 8084
  selector:
    app: payment-service
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: payment-service-hpa
  namespace: shopmetrics
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: payment-service
  minReplicas: 3
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
